### ISSUE TITLE
GradleException: No repositories declared

### ISSUE THREAD

**Issue by ilx** [xvik/gradle-pom-plugin#35]
We recently switched to Gradle 7 and it supports defining repositories via settings.gradle, but once we do it, this plugin fails with:

```
Caused by: org.gradle.api.GradleException: No repositories declared: gradle would not be able to set correct dependencies versions in pom. Use at least: repositories { mavenCentral() }
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at ru.vyarus.gradle.plugin.pom.PomPlugin$_activatePomModifications_closure4$_closure14.doCall(PomPlugin.groovy:123)
```

https://github.com/xvik/gradle-pom-plugin/blob/68be764b5d4750e9c19276a7f1a9b0247f78f617/src/main/groovy/ru/vyarus/gradle/plugin/pom/PomPlugin.groovy#L120-L125

Could it be that it has to check if repositories are defined via settings.gradle in a different way?

**Comment by ilx** [comment]
Maybe related issue: https://github.com/gradle/gradle/issues/17295

**Comment by ilx** [comment]
@xvik Thanks! it works.
